### ISSUE TITLE
@svgo/jsx 0.2.1 is missing exported files

### ISSUE THREAD

**Issue by Mitsunee** [svg/svgo-components#2]
Just upgraded svgo to 2.8.0 and @svgo/jsx to 0.2.1 and saw that my script to build jsx components now fails - turns out the published package is missing some of the files it's supposed to export:

![Screenshot_20211116_195926](https://user-images.githubusercontent.com/19474909/142048663-77ad2d9a-27ce-46f6-a66e-f4273b13e803.png)

Edit: downgrading to v0.2.0 fixed my script

**Comment by TrySound** [comment]
Fixed here https://github.com/svg/svgo-components/releases/tag/v0.2.5

Thanks for reporting.
