### ISSUE TITLE
Support custom targets/renderers like react-native or react-pdf

### ISSUE THREAD

**Issue by jeetiss** [svg/svgo-components#3]
more info https://twitter.com/jeetiss/status/1469198303187423236?s=20

**Comment by tomByrer** [comment]
Could just write once into [Mitosis](https://github.com/BuilderIO/mitosis) which "uses a static form of JSX like Solid".  Then [Mitosis can render](https://mitosis.builder.io/?outputTab=react) into almost any target you want, React, Svelte, Angular, Solid, etc.

**Comment by TrySound** [comment]
Added custom renderers and react-native-svg support in https://github.com/svg/svgo-components/releases/tag/v0.3.0
